---
omejdn:read:
- omejdn
omejdn:write:
- omejdn
omejdn:admin:
- omejdn
profile:
- name
- family_name
- given_name
- middle_name
- nickname
- preferred_username
- profile
- picture
- website
- gender
- birthdate
- zoneinfo
- locale
- updated_at
email:
- email
- email_verified
address:
- formatted
- street_address
- locality
- region
- postal_code
- country
phone:
- phone_number
- phone_number_verified
