---
omejdn:read: Read access to the Omejdn server API
omejdn:write: Write access to the Omejdn server API
omejdn:admin: Access to the Omejdn server admin API
profile: 'Standard profile claims (e.g.: Name, picture, website, gender, birthdate,
  location)'
email: Email-Address
address: Address
phone: Phone-number
