version: "3.9"

services:
  omejdn-daps-server:
    image: ghcr.io/fraunhofer-aisec/omejdn-server:1.4.2
    ports:
      - 4567:4567
    environment:
      OMEJDN_JWT_AUD_OVERRIDE: idsc:IDS_CONNECTORS_ALL
    networks:
      - edc-base-dev
    volumes:
      - ./config/daps/config:/opt/config
      - ./config/daps/keys:/opt/keys

networks:
  edc-base-dev:
    driver: bridge