version: "3.9"

services:
  edc-callback-service:
    build:
      context: edc-callback-service
      args:
        JAR: build/libs/edc-callback-service.jar
    ports:
      - "7081:8080" # default
      - "5011:8090" # debugging
    networks:
      - edc-base-dev

networks:
  edc-base-dev:
    driver: bridge