version: "3.9"

services:
  rd:
    image: ghcr.io/request-dumper/rd:1.0.0
    ports:
      - "3000:3000"
    networks:
      - edc-base-dev

  jaeger:
    image: jaegertracing/all-in-one:1.35
    ports:
      - "6831:6831"
      - "6832:6832"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
      COLLECTOR_OTLP_ENABLED: "true"
    networks:
      - edc-base-dev

networks:
  edc-base-dev:
    driver: bridge
